const spots = [
  {
    "id": 1,
    "name": "枣园北里 12号院",
    "addr": "兴华大街三段 · 小区内部地面车位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 3,
    "cap": 15,
    "window": "19:00-次日8:00",
    "dist": "280m",
    "walk": "4分钟",
    "count": 4,
    "ev": false,
    "monthly": 168,
    "x": 32,
    "y": 38,
    "lng": 116.323627,
    "lat": 39.754978,
    "noSlope": true,
    "size": "standard",
    "covered": false,
    "elevator": true,
    "code": "ZY-B07",
    "rule": "夜间封顶 ¥15，白天需在 8:00 前驶离",
    "occupancy": 72
  },
  {
    "id": 2,
    "name": "大兴荟聚 P2",
    "addr": "欣宁街 15 号 · 商场地下车库 P2 层",
    "type": "mall",
    "badge": "商场认证",
    "rate": 2,
    "cap": 12,
    "window": "22:00-次日9:00",
    "dist": "450m",
    "walk": "6分钟",
    "count": 23,
    "ev": true,
    "monthly": 168,
    "x": 58,
    "y": 30,
    "lng": 116.327525,
    "lat": 39.787658,
    "noSlope": true,
    "size": "large",
    "covered": true,
    "elevator": true,
    "code": "P2-089",
    "rule": "车牌识别自动抬杆，P2 有 8 个充电位",
    "occupancy": 54
  },
  {
    "id": 3,
    "name": "魏师傅的车位",
    "addr": "高米店南 3 栋 102 · 产权私家车位",
    "type": "personal",
    "badge": "个人车位",
    "rate": 4,
    "cap": 0,
    "window": "08:00-18:00",
    "dist": "190m",
    "walk": "3分钟",
    "count": 1,
    "ev": false,
    "monthly": 0,
    "x": 44,
    "y": 55,
    "lng": 116.331605,
    "lat": 39.763489,
    "noSlope": false,
    "size": "standard",
    "covered": false,
    "elevator": false,
    "code": "WSF-01",
    "rule": "车主白天上班出借，18:00 前须驶离",
    "occupancy": 31
  },
  {
    "id": 4,
    "name": "生物医药基地 P1",
    "addr": "永大路 38 号 · 企业错峰车位",
    "type": "mall",
    "badge": "企业认证",
    "rate": 2.5,
    "cap": 14,
    "window": "19:00-次日8:30",
    "dist": "620m",
    "walk": "9分钟",
    "count": 15,
    "ev": true,
    "monthly": 198,
    "x": 70,
    "y": 62,
    "lng": 116.299709,
    "lat": 39.687555,
    "noSlope": true,
    "size": "bus",
    "covered": true,
    "elevator": false,
    "code": "BIO-A12",
    "rule": "需从东门闸机进入，凭订单码抬杆",
    "occupancy": 46
  },
  {
    "id": 5,
    "name": "黄村西里 5号院",
    "addr": "兴丰大街 · 老旧小区免费共享位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "19:00-次日8:00",
    "dist": "350m",
    "walk": "5分钟",
    "count": 2,
    "ev": false,
    "monthly": 0,
    "x": 24,
    "y": 66,
    "lng": 116.33917,
    "lat": 39.73682,
    "noSlope": true,
    "size": "large",
    "covered": false,
    "elevator": true,
    "code": "HC-05",
    "rule": "老旧小区夜间免费共享，需按时驶离",
    "occupancy": 83
  },
  {
    "id": 6,
    "name": "李阿姨的车位",
    "addr": "旧宫德茂家园 7 栋前 · 产权私家车位",
    "type": "personal",
    "badge": "个人车位",
    "rate": 3,
    "cap": 0,
    "window": "全天可约",
    "dist": "520m",
    "walk": "8分钟",
    "count": 1,
    "ev": false,
    "monthly": 0,
    "x": 80,
    "y": 44,
    "lng": 116.438754,
    "lat": 39.778045,
    "noSlope": false,
    "size": "large",
    "covered": false,
    "elevator": false,
    "code": "LAA-06",
    "rule": "长租优先，可与车主协商包月",
    "occupancy": 35
  },
  {
    "id": 7,
    "name": "康庄老旧小区东院",
    "addr": "康庄路 · 居委会夜间免费车位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "20:00-次日7:30",
    "dist": "680m",
    "walk": "10分钟",
    "count": 8,
    "ev": false,
    "monthly": 0,
    "x": 18,
    "y": 42,
    "lng": 116.342233,
    "lat": 39.755599,
    "noSlope": true,
    "size": "standard",
    "covered": false,
    "elevator": true,
    "code": "KZ-07",
    "rule": "免费错峰共享，需登记车牌",
    "occupancy": 62
  },
  {
    "id": 8,
    "name": "清源西里北门",
    "addr": "清源路 · 老旧小区划线共享位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "18:30-次日8:00",
    "dist": "760m",
    "walk": "11分钟",
    "count": 5,
    "ev": false,
    "monthly": 0,
    "x": 38,
    "y": 24,
    "lng": 116.335119,
    "lat": 39.744259,
    "noSlope": true,
    "size": "standard",
    "covered": false,
    "elevator": false,
    "code": "QY-08",
    "rule": "免费车位先到先得，预约后保留 10 分钟",
    "occupancy": 70
  },
  {
    "id": 9,
    "name": "兴丰家园社区泊位",
    "addr": "兴丰北大街 · 社区公共泊位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "全天可约",
    "dist": "930m",
    "walk": "13分钟",
    "count": 12,
    "ev": false,
    "monthly": 0,
    "x": 13,
    "y": 72,
    "lng": 116.339767,
    "lat": 39.735022,
    "noSlope": true,
    "size": "large",
    "covered": false,
    "elevator": true,
    "code": "XF-09",
    "rule": "社区便民免费位，大车优先停靠外侧",
    "occupancy": 57
  },
  {
    "id": 10,
    "name": "高米店企业园 P3",
    "addr": "金星西路 · 企业错峰地下车位",
    "type": "mall",
    "badge": "企业认证",
    "rate": 2.2,
    "cap": 13,
    "window": "19:00-次日8:30",
    "dist": "1.1km",
    "walk": "15分钟",
    "count": 32,
    "ev": true,
    "monthly": 188,
    "x": 64,
    "y": 40,
    "lng": 116.332354,
    "lat": 39.765082,
    "noSlope": true,
    "size": "large",
    "covered": true,
    "elevator": true,
    "code": "GMD-P3",
    "rule": "园区批量接入，车牌识别入场",
    "occupancy": 42
  },
  {
    "id": 11,
    "name": "大兴机场换乘 P5",
    "addr": "机场北线 · 大客车临停区",
    "type": "mall",
    "badge": "企业认证",
    "rate": 4,
    "cap": 28,
    "window": "全天可约",
    "dist": "1.8km",
    "walk": "换乘8分钟",
    "count": 60,
    "ev": true,
    "monthly": 0,
    "x": 83,
    "y": 71,
    "lng": 116.43028,
    "lat": 39.558983,
    "noSlope": true,
    "size": "bus",
    "covered": true,
    "elevator": false,
    "code": "PKX-P5",
    "rule": "支持大客车与新能源车，需从北门进入",
    "occupancy": 50
  },
  {
    "id": 12,
    "name": "旧宫地铁站 P+R",
    "addr": "旧宫站东侧 · 换乘停车场",
    "type": "mall",
    "badge": "站点认证",
    "rate": 1.5,
    "cap": 10,
    "window": "06:00-23:00",
    "dist": "1.4km",
    "walk": "地铁2站",
    "count": 45,
    "ev": true,
    "monthly": 138,
    "x": 78,
    "y": 22,
    "lng": 116.460789,
    "lat": 39.80691,
    "noSlope": true,
    "size": "standard",
    "covered": false,
    "elevator": true,
    "code": "JG-PR",
    "rule": "换乘优惠，需绑定地铁乘车记录",
    "occupancy": 48
  },
  {
    "id": 13,
    "name": "观音寺街道共享位",
    "addr": "观音寺南里 · 免费错峰泊位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "19:00-次日8:00",
    "dist": "610m",
    "walk": "9分钟",
    "count": 6,
    "ev": false,
    "monthly": 0,
    "x": 28,
    "y": 49,
    "lng": 116.349591,
    "lat": 39.723947,
    "noSlope": true,
    "size": "standard",
    "covered": false,
    "elevator": true,
    "code": "GYS-13",
    "rule": "居委会认证免费共享，限小型车",
    "occupancy": 66
  },
  {
    "id": 14,
    "name": "绿地缤纷城 P1",
    "addr": "金星西路 · 商场地下车库 P1",
    "type": "mall",
    "badge": "商场认证",
    "rate": 3,
    "cap": 18,
    "window": "10:00-22:30",
    "dist": "820m",
    "walk": "12分钟",
    "count": 38,
    "ev": true,
    "monthly": 218,
    "x": 52,
    "y": 72,
    "lng": 116.334588,
    "lat": 39.763598,
    "noSlope": true,
    "size": "large",
    "covered": true,
    "elevator": true,
    "code": "LD-P1",
    "rule": "P1 近电梯厅，新能源位 12 个",
    "occupancy": 44
  },
  {
    "id": 15,
    "name": "大悦春风里 P3",
    "addr": "黄村东大街 · 商场地下车库",
    "type": "mall",
    "badge": "商场认证",
    "rate": 2.8,
    "cap": 16,
    "window": "09:30-23:00",
    "dist": "1.2km",
    "walk": "公交8分钟",
    "count": 41,
    "ev": true,
    "monthly": 208,
    "x": 61,
    "y": 76,
    "lng": 116.3413,
    "lat": 39.730841,
    "noSlope": true,
    "size": "large",
    "covered": true,
    "elevator": true,
    "code": "DY-P3",
    "rule": "电梯直达商场，宽车位优先",
    "occupancy": 41
  },
  {
    "id": 16,
    "name": "狼垡社区夜间共享",
    "addr": "狼垡东路 · 老旧小区免费位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "20:00-次日7:00",
    "dist": "1.6km",
    "walk": "公交10分钟",
    "count": 14,
    "ev": false,
    "monthly": 0,
    "x": 10,
    "y": 34,
    "lng": 116.290453,
    "lat": 39.77663,
    "noSlope": true,
    "size": "large",
    "covered": false,
    "elevator": false,
    "code": "LF-16",
    "rule": "免费开放，需避让消防通道",
    "occupancy": 59
  },
  {
    "id": 17,
    "name": "瀛海家园闲置位",
    "addr": "瀛吉街 · 小区错峰车位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 1,
    "cap": 8,
    "window": "18:00-次日8:00",
    "dist": "1.7km",
    "walk": "公交12分钟",
    "count": 9,
    "ev": false,
    "monthly": 98,
    "x": 88,
    "y": 55,
    "lng": 116.436589,
    "lat": 39.76274,
    "noSlope": true,
    "size": "standard",
    "covered": false,
    "elevator": true,
    "code": "YH-17",
    "rule": "低价便民，夜间封顶 ¥8",
    "occupancy": 53
  },
  {
    "id": 18,
    "name": "西红门产业园 P2",
    "addr": "宏业路 · 园区批量车位",
    "type": "mall",
    "badge": "企业认证",
    "rate": 2,
    "cap": 12,
    "window": "19:00-次日8:30",
    "dist": "1.5km",
    "walk": "公交9分钟",
    "count": 76,
    "ev": true,
    "monthly": 168,
    "x": 72,
    "y": 50,
    "lng": 116.332659,
    "lat": 39.784979,
    "noSlope": true,
    "size": "bus",
    "covered": true,
    "elevator": false,
    "code": "XHM-P2",
    "rule": "企业批量开放，支持大车与充电",
    "occupancy": 36
  },
  {
    "id": 19,
    "name": "榆垡便民停车场",
    "addr": "榆垡镇政府旁 · 免费公共车位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "全天可约",
    "dist": "2.1km",
    "walk": "驾车6分钟",
    "count": 24,
    "ev": false,
    "monthly": 0,
    "x": 86,
    "y": 82,
    "lng": 116.315551,
    "lat": 39.511364,
    "noSlope": true,
    "size": "bus",
    "covered": false,
    "elevator": false,
    "code": "YF-19",
    "rule": "免费公共停车场，大客车可停外圈",
    "occupancy": 40
  },
  {
    "id": 20,
    "name": "庞各庄临时停车场",
    "addr": "瓜乡桥旁 · 免费临时停车区",
    "type": "community",
    "badge": "街道认证",
    "rate": 0,
    "cap": 0,
    "window": "全天可约",
    "dist": "2.4km",
    "walk": "驾车8分钟",
    "count": 30,
    "ev": false,
    "monthly": 0,
    "x": 20,
    "y": 82,
    "lng": 116.325392,
    "lat": 39.620824,
    "noSlope": true,
    "size": "bus",
    "covered": false,
    "elevator": false,
    "code": "PGZ-20",
    "rule": "免费临停，大车需停指定区域",
    "occupancy": 45
  },
  {
    "id": 21,
    "name": "金星庄园个人位",
    "addr": "金星庄园 9 栋地下 · 个人车位",
    "type": "personal",
    "badge": "个人车位",
    "rate": 2,
    "cap": 10,
    "window": "全天可约",
    "dist": "540m",
    "walk": "8分钟",
    "count": 1,
    "ev": true,
    "monthly": 158,
    "x": 48,
    "y": 43,
    "lng": 116.383145,
    "lat": 39.7619,
    "noSlope": true,
    "size": "standard",
    "covered": true,
    "elevator": true,
    "code": "JX-21",
    "rule": "车主长期出借，带 7kW 慢充",
    "occupancy": 28
  },
  {
    "id": 22,
    "name": "西红门老街胡同位",
    "addr": "西红门路 · 老街免费共享位",
    "type": "community",
    "badge": "居委会认证",
    "rate": 0,
    "cap": 0,
    "window": "19:30-次日7:30",
    "dist": "1.3km",
    "walk": "公交8分钟",
    "count": 4,
    "ev": false,
    "monthly": 0,
    "x": 34,
    "y": 78,
    "lng": 116.330093,
    "lat": 39.794446,
    "noSlope": false,
    "size": "standard",
    "covered": false,
    "elevator": false,
    "code": "XHM-22",
    "rule": "免费共享，胡同较窄不建议大车",
    "occupancy": 78
  },
  {
    "id": 23,
    "name": "兴华桥下错峰位",
    "addr": "兴华大街桥下 · 街道错峰车位",
    "type": "community",
    "badge": "街道认证",
    "rate": 1,
    "cap": 6,
    "window": "18:00-次日8:00",
    "dist": "420m",
    "walk": "6分钟",
    "count": 18,
    "ev": false,
    "monthly": 88,
    "x": 42,
    "y": 63,
    "lng": 116.332493,
    "lat": 39.751847,
    "noSlope": true,
    "size": "large",
    "covered": true,
    "elevator": false,
    "code": "XHQ-23",
    "rule": "桥下遮雨，低价错峰开放",
    "occupancy": 49
  },
  {
    "id": 24,
    "name": "大兴政务中心 P1",
    "addr": "永华路 · 政务中心地下车库",
    "type": "mall",
    "badge": "政务认证",
    "rate": 2,
    "cap": 12,
    "window": "18:30-次日8:30",
    "dist": "970m",
    "walk": "14分钟",
    "count": 28,
    "ev": true,
    "monthly": 168,
    "x": 66,
    "y": 28,
    "lng": 116.328459,
    "lat": 39.724832,
    "noSlope": true,
    "size": "large",
    "covered": true,
    "elevator": true,
    "code": "ZW-P1",
    "rule": "晚间开放社会车辆，近电梯无坡道",
    "occupancy": 38
  }
];

const orders = [
  { id: "CP20260711001", name: "大兴荟聚 P2 · P2-089", time: "昨天 22:10 - 今天 07:42", amount: "¥12.0", state: "已完成" },
  { id: "CP20260709018", name: "枣园北里 12号院", time: "7月8日 19:33 - 23:05", amount: "¥10.5", state: "已完成" },
  { id: "CP20260706007", name: "魏师傅的车位", time: "7月6日 09:00 - 11:20", amount: "¥8.0", state: "已退款" }
];

const owner = {
  renting: true,
  revenueToday: 38,
  revenueWeek: 268,
  spot: {
    name: "枣园北里 · B-07",
    window: "工作日 08:30 - 18:00",
    price: "¥4 / 时",
    status: "出租中"
  },
  enterprise: {
    company: "北京生物医药基地园区",
    lots: 126,
    activeLots: 84,
    weeklyRevenue: 18320,
    openHours: "工作日 19:00 - 次日 08:30",
    adoption: 67,
    rows: [
      { area: "P1 东区", total: 46, shared: 32, revenue: "¥6,820", status: "已上线" },
      { area: "P1 西区", total: 38, shared: 24, revenue: "¥4,910", status: "已上线" },
      { area: "地面访客区", total: 22, shared: 16, revenue: "¥3,250", status: "审核中" },
      { area: "员工临停车区", total: 20, shared: 12, revenue: "¥3,340", status: "待联调" }
    ]
  }
};

const bookings = [];

module.exports = {
  spots,
  orders,
  owner,
  bookings
};
